spring:
  # ?????
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/waimai?serverTimezone=UTC
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://localhost/waimai
#???
oss:
  qiniu:
    domain: http://r98osdghy.hd-bkt.clouddn.com
    accessKey: Q7PuwyN8TZBBWrdBYjlIP7ntmh3qdC2e74IMiUFL
    secretKey: 0bpwMTVOC71JTCyb6dFMgQBAgZeYTNt5aL6SAOXR
    bucketName: shanyu0-health

#????
logging:
  pattern:
    console: "%date{HH:mm:ss.SSS} %-5level %-30.30logger{29} : %msg%n"
  level:
    com.demo: DEBUG
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
